apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  selector:
    app: grpc-server
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - name: grpc
      protocol: TCP
      port: 10000  # no targetPort for headless service
